relevant_sections_task:
  description: >
    Given the table of contents, identify which sections are most likely to contain {topic} data. The table of contents is a json object, which contains titles, chapters and sections. 
    The sections are nested under the chapters and the chapters are nested under the titles. Here the table of contents: 
    
    {table_of_contents}
  expected_output: >
    An ordered list of sections that are most likely to contain {topic} data, ranked by relevance. Only return the section titles, not the content.
  agent: documents_analyst

